### ISSUE TITLE
Pointer on Pointer of NSString creates an Error

### ISSUE THREAD

**Issue by klein-artur** [sheldon/sequel-pro#2]
File: SPMySQLResult.h

``` objective-c
NSString **fieldNames;
```

This line leads to the error Pointer to non-const type 'NSString *' with no explicit ownership

If you change this line to 

``` objective-c
NSString *__strong *fieldNames;
```

then it works fine.

I´m working on xcode 8

regards

Artur

**Comment by sheldon** [comment]
Hey

I'm afraid I only made this clone to try hacking on the code a little, please could you resubmit his at https://github.com/sequelpro/sequelpro
